[package]
name = "pixirust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.13.0"
chrono = { version = "0.4.19", features = ["serde"] }
hex = "0.4.3"
hmac = "0.11.0"
lazy_static = "1.4.0"
rand = "0.8.4"
regex = "1.5.4"
reqwest = { vesion = "0.11.8", features = ["socks"] }
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.70"
sha2 = "0.9.8"
tokio = { version = "1.14.0", features = ["macros"] }
urlencoding = "2.1.0"
uuid = { version = "0.8.2", features = ["v4"] }
